version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      ENABLE_MODULES: ""
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
      GRPC_PORT: "50051"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_LSM_ACCESS_STRATEGY: "mmap"  # improves throughput for read-heavy workloads
      QUERY_DEFAULTS_LIMIT: 200  # increase default query result limit
      VECTOR_INDEX_TYPE: "hnsw"
      VECTOR_INDEX_DISTANCE: "cosine"
      VECTOR_INDEX_EFCONSTRUCTION: 128  # increase search quality during index construction
      VECTOR_INDEX_EF: 128  # increase search quality during querying
      VECTOR_INDEX_MAXCONNECTIONS: 64  # increase graph connectivity
      LIMIT_RESOURCES_MEM: ${MEM_LIMIT:-"4Gi"}  # adjust based on available memory
      LIMIT_RESOURCES_CPU: ${CPU_LIMIT:-"2"}  # CPU limit
      DISK_USE_WARN_PERCENTAGE: 90
      AUTO_SCHEMA_ENABLED: "false"  # disable auto schema for improved stability
      PERSISTENCE_SNAPSHOT_INTERVAL: "30m"  # More frequent snapshots
      LOG_LEVEL: "info"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - entity_resolution_network
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-2}'
          memory: ${MEM_LIMIT:-4G}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  entity_resolution_network:
    driver: bridge

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - weaviate

volumes:
  weaviate_data:
    driver: local
  prometheus_data:
    driver: local