global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "weaviate"
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["weaviate:8080"]

  - job_name: "entity_resolution"
    static_configs:
      - targets: ["host.docker.internal:8000"]
